In [1]:
import numpy as np

## 1. Creating a Numpy array

### 1-D array

In [2]:
myarr1 = np.array([3,6,78,23] , np.int64)
myarr1

array([ 3,  6, 78, 23], dtype=int64)

In [3]:
myarr1[2]

78

### 2-D array

In [4]:
myarr = np.array([[3,6,78,23]] , np.int64)
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

## 2. Array creation methods

In [8]:
Zeros = np.zeros((2,5))  # it makes array of zeros
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
rng = np.arange(15)  # it makes array within given range
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
lsp = np.linspace(1,50,10) # it creates array of equally spaced 10 no., from 1 to 50
lsp

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [13]:
emp = np.empty((4,6)) # it makes empty array having random value
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.95812747e-306, 8.90104918e-307],
       [2.13620807e-306, 1.69120552e-306, 1.69120552e-306,
        8.06638080e-308, 1.24611674e-306, 8.34447259e-308],
       [2.22522597e-306, 8.06637656e-308, 9.45698830e-308,
        1.33508336e-307, 1.16820961e-307, 1.11257767e-307],
       [1.78022342e-306, 2.44776798e-307, 1.69119330e-306,
        8.01097889e-307, 1.78022342e-306, 2.33423131e-312]])

In [16]:
ide = np.identity(45) # it makes a identity matrix 
ide

(45, 45)

# 2. Some operations on numpy array

In [7]:
myarr[0,1] = 45  # to change value in our array
myarr

array([[ 3, 45, 78, 23]], dtype=int64)

### Reshaping of array (Conversion between 1-D and 2-D array)

In [17]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr.shape

(99,)

# 3. Numpy array Axis

In [23]:
x = [[1,2,3],[4,6,9],[7,12,14]]  # 2-D array having 2 axis, axis-0 -> columns and axis-1 -> rows

In [25]:
ar = np.array(x)
ar

array([[ 1,  2,  3],
       [ 4,  6,  9],
       [ 7, 12, 14]])

In [26]:
ar.sum(axis=0)

array([12, 20, 26])

In [27]:
ar.sum(axis=1)

array([ 6, 19, 33])

# 4. Attributes of numpy

In [30]:
ar

array([[ 1,  2,  3],
       [ 4,  6,  9],
       [ 7, 12, 14]])

In [31]:
ar.ndim  # it shows no. of dimensions of our array

2

In [28]:
ar.T  # it transpose the matrix

array([[ 1,  4,  7],
       [ 2,  6, 12],
       [ 3,  9, 14]])

In [29]:
ar.flat  # it flat our 2D array
for item in ar.flat:
    print(item)

1
2
3
4
6
9
7
12
14


In [32]:
ar.size 

9

In [34]:
ar.nbytes # it shows total bytes consumed

36

# 5. Methods of numpy

In [39]:
one = np.array([1,3,54,78,2,13])

In [40]:
one.argmax() # it gives index of largest element present in our array

3

In [41]:
one.argsort()

array([0, 4, 1, 5, 2, 3], dtype=int64)

# 6. Maths in numpy

In [42]:
ar

array([[ 1,  2,  3],
       [ 4,  6,  9],
       [ 7, 12, 14]])

In [43]:
ar2 = np.array([[ 1,  9,  31],
       [ 43,  6,  12],
       [ 7, 72, 19]])
ar2

array([[ 1,  9, 31],
       [43,  6, 12],
       [ 7, 72, 19]])

In [45]:
ar + ar2

array([[ 2, 11, 34],
       [47, 12, 21],
       [14, 84, 33]])

In [46]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.44948974, 3.        ],
       [2.64575131, 3.46410162, 3.74165739]])

In [47]:
ar.sum()

58

In [48]:
ar.max()

14

In [51]:
ar

array([[ 1,  2,  3],
       [ 4,  6,  9],
       [ 7, 12, 14]])

In [56]:
np.count_nonzero(ar)

9